spring:
  application:
    name: onboarding-auth-service

server:
  port: 9000   # HTTP (Tomcat) port

auth:
  service:
    client: "onboarding_client"
    secret: "5yynnKSq4ERW23cJ"
    scope: "ONBOARDING"

onboarding:
  client:
    user: "onboarding"
    password: "mxTSms6aeQptCzCJ"

jwt:
  singning:
    key: "AmPkxJZf=YH%uVprWueg23s^&4w5r_5H5_$RCznr"